[package]
name = "rust-token-server"
description = "Authentication server handling id token in the context of OIDC"
version = "0.1.2"
authors = ["Jun Kurihara"]
homepage = "https://github.com/junkurihara/rust-token-server"
repository = "https://github.com/junkurihara/rust-token-server"
license = "MIT"
readme = "README.md"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["json"] }
serde = "1.0.137"
rusqlite = "0.27.0"
anyhow = "1.0.57"
rust-argon2 = "1.0.0"
rand = "0.8.5"
env_logger = "0.9.0"
log = "0.4.17"
clap = { version = "3.1.17", default-features = false, features = [
  "std",
  "cargo",
  "wrap_help",
] }
p256 = { version = "0.11.0", features = ["pem", "jwk", "default"] }
jwt-simple = { git = "https://github.com/junkurihara/rust-jwt-simple" }
# jwt-simple = "0.11.0"
base64 = "0.13.0"
serde_json = "1.0.81"
chrono = "0.4.19"
url = "2.2.2"
fallible-streaming-iterator = "0.1.9"
uuid = { version = "1.0.0", features = ["v4"] }


[profile.release]
codegen-units = 1
incremental = false
lto = "fat"
opt-level = 3
panic = "abort"
