[package]
name = "rust-token-server"
description = "Authentication server handling id token in the context of OIDC"
version = "0.1.3"
authors = ["Jun Kurihara"]
homepage = "https://github.com/junkurihara/rust-token-server"
repository = "https://github.com/junkurihara/rust-token-server"
license = "MIT"
readme = "README.md"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["json"] }
serde = "1.0.147"
rusqlite = "0.28.0"
anyhow = "1.0.66"
rust-argon2 = "1.0.0"
rand = "0.8.5"
env_logger = "0.9.1"
log = "0.4.17"
clap = { version = "4.0.18", default-features = false, features = [
  "std",
  "cargo",
  "wrap_help",
] }
p256 = { version = "0.11.1", features = ["pem", "jwk", "default"] }
jwt-simple = { git = "https://github.com/junkurihara/rust-jwt-simple" }
base64 = "0.13.1"
serde_json = "1.0.87"
chrono = "0.4.22"
url = "2.3.1"
fallible-streaming-iterator = "0.1.9"
uuid = { version = "1.2.1", features = ["v4"] }


[profile.release]
codegen-units = 1
incremental = false
lto = "fat"
opt-level = 3
panic = "abort"
