[package]
name = "rust-token-server"
version = "0.1.0"
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["json"] }
serde = "1.0.130"
rusqlite = "0.26.1"
anyhow = "1.0.45"
rust-argon2 = "0.8.3"
rand = "0.8.4"
env_logger = "0.9.0"
log = "0.4.14"
clap = "2.33.3"
p256 = { version = "0.9.0", features = ["pem", "jwk", "default"] }
jwt-simple = "0.10.7"
base64 = "0.13.0"
serde_json = "1.0.70"
chrono = "0.4.19"
url = "2.2.2"
fallible-streaming-iterator = "0.1.9"
uuid = { version = "0.8.2", features = ["v4"] }


[profile.release]
codegen-units = 1
incremental = false
lto = "fat"
opt-level = 3
panic = "abort"
