[package]
name = "rust-token-server"
description = "Authentication server handling id token in the context of OIDC"
version = "0.1.3"
authors = ["Jun Kurihara"]
homepage = "https://github.com/junkurihara/rust-token-server"
repository = "https://github.com/junkurihara/rust-token-server"
license = "MIT"
readme = "README.md"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["p256", "ed25519-dalek"]

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["json"] }
serde = "1.0.152"
rusqlite = "0.28.0"
anyhow = "1.0.69"
rust-argon2 = "1.0.0"
rand = "0.8.5"
env_logger = "0.10.0"
log = "0.4.17"
clap = { version = "4.1.8", default-features = false, features = [
  "std",
  "cargo",
  "wrap_help",
] }
jwt-simple = "0.11.4"
base64 = "0.21.0"
serde_json = "1.0.94"
chrono = "0.4.23"
url = "2.3.1"
fallible-streaming-iterator = "0.1.9"
uuid = { version = "1.3.0", features = ["v4"] }

[dependencies.p256]
version = "0.13.0"
features = ["pem", "jwk", "default"]
optional = true

[dependencies.ed25519-dalek]
git = "https://github.com/dalek-cryptography/ed25519-dalek"
# version = "2.0.0-pre.0"
features = ["pem", "default"]
optional = true


[profile.release]
codegen-units = 1
incremental = false
lto = "fat"
opt-level = 3
panic = "abort"
