[package]
name = "rust-token-server"
description = "Authentication server handling id token in the context of OIDC"
version = "0.3.2"
authors = ["Jun Kurihara"]
homepage = "https://github.com/junkurihara/rust-token-server"
repository = "https://github.com/junkurihara/rust-token-server"
license = "MIT"
readme = "../README.md"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libcommon = { path = "../common", package = "rust-token-server-common" }

anyhow = "1.0.77"
axum = { version = "0.7.2" }
base64 = "0.21.5"
chrono = "0.4.31"
clap = { version = "4.4.11", features = ["std", "cargo", "wrap_help"] }
jwt-simple = "0.12.6"
rand = "0.8.5"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
tokio = { version = "1.35.1", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
sqlx = { version = "0.7.3", features = ["sqlite", "runtime-tokio-rustls"] }
async-trait = "0.1.75"
uuid = { version = "1.6.1", features = ["v4"] }
validator = { version = "0.16", features = ["derive"] }
rust-argon2 = "2.0.0"
jwt-compact = { version = "0.8.0", features = ["p256", "ed25519-compact"] }
url = "2.5.0"
