[package]
name = "rust-token-server"
description = "Authentication server handling id token in the context of OIDC"
version = "0.3.1"
authors = ["Jun Kurihara"]
homepage = "https://github.com/junkurihara/rust-token-server"
repository = "https://github.com/junkurihara/rust-token-server"
license = "MIT"
readme = "../README.md"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
axum = { version = "0.6.20", features = ["headers"] }
base64 = "0.21.4"
chrono = "0.4.31"
clap = { version = "4.4.6", features = ["std", "cargo", "wrap_help"] }
jwt-simple = "0.11.7"
rand = "0.8.5"
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
tokio = { version = "1.33.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
sqlx = { version = "0.7.2", features = ["sqlite", "runtime-tokio-rustls"] }
async-trait = "0.1.74"
uuid = { version = "1.5.0", features = ["v4"] }
validator = { version = "0.16", features = ["derive"] }
rust-argon2 = "2.0.0"
jwt-compact = { version = "0.8.0", features = ["p256", "ed25519-compact"] }
url = "2.4.1"
