[package]
name = "rust-token-server-client"
version = "0.1.0"
edition = "2021"
description = "Client library for `rust-token-server`"
authors = ["Jun Kurihara"]
homepage = "https://github.com/junkurihara/rust-token-server"
repository = "https://github.com/junkurihara/rust-token-server"
license = "MIT"
readme = "../README.md"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.40"
anyhow = "1.0.75"
url = "2.4.1"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
chrono = "0.4.31"
jwt-simple = "0.11.9"
p256 = { version = "0.13.2", features = ["jwk", "pem"] }
tokio = { version = "1.34.0", features = [
  "net",
  "rt-multi-thread",
  "time",
  "sync",
  "macros",
] }
async-trait = "0.1.74"
base64 = "0.21.5"
thiserror = "1.0.50"


[dev-dependencies]
reqwest = { version = "0.11.22", default-features = false, features = [
  "json",
  "trust-dns",
  "default",
] }
