name: Unit Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run unit tests for rust-token-server-common
        run: |
          cargo test --verbose --package rust-token-server-common

      - name: Run unit tests for rust-token-server
        run: |
          cargo test --verbose --package rust-token-server

      - name: Run unit tests for rust-token-server-client and rust-token-server-validator
        run: |
          bash client_validator_test.sh
